product_types:
  security:
    name: security
    critical_product: true
    key_product: true
  nfvi:
    name: nfvi
    critical_product: true
    key_product: true
  cicd:
    name: cicd
    critical_product: true
    key_product: true
  dt_related:
    name: dt_related
    critical_product: false
    key_product: false
